# yaml stands for "YAML Ain't Markup Language", Yet Another Markup Language
name: CI Pipeline



on:
  push:
    branches:
        - main
        - any-feature-branch



jobs:
    
    job1:
        runs-on: ubuntu-latest # can even have macos-latest or windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4  # v4 is the version of the action we're using, not the branch of the code; https://github.com/actions/checkout 
        # purpose of checkout code is to get the code from the repository, and put it in the runner machine
        
            - name: Set up Python
              uses: actions/setup-python@v5  # v4 is the version of the action we're using, not the branch of the code;
              with:
                python-version: '3.10'  # Specify the Python version you want to use

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r session_6_CI/requirements.txt  # Install dependencies from requirements.txt
            
            - name: Run tests
              run: |
                    pytest
